spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${PORT:9090}

security:
  cookie:
    secure: ${REFRESH_COOKIE_SECURE}
  cors:
    allowed-origins:
      - ${ORMAN_FRONTEND_URL}

orman:
  storage:
    provider: ${ORMAN_STORAGE_PROVIDER}
