CREATE TABLE cuentas_pago (
    codcta INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codper_propietaria INTEGER NOT NULL,
    banco VARCHAR(100) NOT NULL,
    numero_cuenta VARCHAR(100) NOT NULL,
    titular VARCHAR(200) NOT NULL,
    qr_url VARCHAR(500),
    instrucciones VARCHAR(1000),
    orden INTEGER NOT NULL,
    estado SMALLINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_cuentas_pago PRIMARY KEY (codcta),
    CONSTRAINT fk_cuentas_pago_personas FOREIGN KEY (codper_propietaria)
        REFERENCES personas (codper) ON DELETE RESTRICT,
    CONSTRAINT uk_cuentas_pago_propietaria_banco_numero
        UNIQUE (codper_propietaria, banco, numero_cuenta),
    CONSTRAINT uk_cuentas_pago_propietaria_orden UNIQUE (codper_propietaria, orden),
    CONSTRAINT ck_cuentas_pago_orden CHECK (orden >= 0),
    CONSTRAINT ck_cuentas_pago_estado CHECK (estado IN (0, 1))
);

CREATE INDEX ix_cuentas_pago_propietaria ON cuentas_pago (codper_propietaria);

CREATE TABLE pagos (
    codpag INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codcuo INTEGER NOT NULL,
    codcta INTEGER,
    monto NUMERIC(14, 2) NOT NULL,
    metodo VARCHAR(20) NOT NULL,
    referencia_externa VARCHAR(100),
    fecha_pago TIMESTAMP NOT NULL,
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(25) NOT NULL DEFAULT 'PENDIENTE_REVISION',
    origen VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    idempotency_key UUID NOT NULL,
    fecha_revision TIMESTAMP,
    motivo_rechazo VARCHAR(500),
    motivo_anulacion VARCHAR(500),
    CONSTRAINT pk_pagos PRIMARY KEY (codpag),
    CONSTRAINT fk_pagos_cuotas FOREIGN KEY (codcuo)
        REFERENCES cuotas (codcuo) ON DELETE RESTRICT,
    CONSTRAINT fk_pagos_cuentas_pago FOREIGN KEY (codcta)
        REFERENCES cuentas_pago (codcta) ON DELETE RESTRICT,
    CONSTRAINT uk_pagos_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_pagos_monto CHECK (monto > 0),
    CONSTRAINT ck_pagos_metodo CHECK (metodo IN ('EFECTIVO', 'TRANSFERENCIA', 'QR')),
    CONSTRAINT ck_pagos_estado CHECK (estado IN ('PENDIENTE_REVISION', 'CONFIRMADO', 'RECHAZADO', 'ANULADO')),
    CONSTRAINT ck_pagos_origen CHECK (origen IN ('MANUAL', 'MOVIL')),
    CONSTRAINT ck_pagos_cuenta_por_metodo CHECK (
        (metodo = 'EFECTIVO' AND codcta IS NULL)
        OR (metodo IN ('TRANSFERENCIA', 'QR') AND codcta IS NOT NULL)
    ),
    CONSTRAINT ck_pagos_revision_por_estado CHECK (
        (estado = 'PENDIENTE_REVISION' AND fecha_revision IS NULL
            AND motivo_rechazo IS NULL AND motivo_anulacion IS NULL)
        OR (estado = 'CONFIRMADO' AND fecha_revision IS NOT NULL
            AND motivo_rechazo IS NULL AND motivo_anulacion IS NULL)
        OR (estado = 'RECHAZADO' AND fecha_revision IS NOT NULL
            AND motivo_rechazo IS NOT NULL AND motivo_anulacion IS NULL)
        OR (estado = 'ANULADO' AND fecha_revision IS NOT NULL
            AND motivo_rechazo IS NULL AND motivo_anulacion IS NOT NULL)
    )
);

CREATE INDEX ix_pagos_codcuo_estado ON pagos (codcuo, estado);
CREATE INDEX ix_pagos_codcta ON pagos (codcta);
CREATE UNIQUE INDEX uk_pagos_codcta_referencia_externa
    ON pagos (codcta, referencia_externa)
    WHERE referencia_externa IS NOT NULL;

CREATE TABLE pago_comprobantes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codpag INTEGER NOT NULL,
    url VARCHAR(500) NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    tipo_contenido VARCHAR(100) NOT NULL,
    orden INTEGER NOT NULL,
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_pago_comprobantes PRIMARY KEY (id),
    CONSTRAINT fk_pago_comprobantes_pagos FOREIGN KEY (codpag)
        REFERENCES pagos (codpag) ON DELETE RESTRICT,
    CONSTRAINT uk_pago_comprobantes_codpag_orden UNIQUE (codpag, orden),
    CONSTRAINT ck_pago_comprobantes_orden CHECK (orden >= 0)
);

CREATE INDEX ix_pago_comprobantes_codpag ON pago_comprobantes (codpag);

CREATE TABLE recibos (
    codrec INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codpag INTEGER NOT NULL,
    fecha_emision TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_recibos PRIMARY KEY (codrec),
    CONSTRAINT fk_recibos_pagos FOREIGN KEY (codpag)
        REFERENCES pagos (codpag) ON DELETE RESTRICT,
    CONSTRAINT uk_recibos_codpag UNIQUE (codpag)
);

CREATE INDEX ix_recibos_codpag ON recibos (codpag);
